asian_kitchen_web/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('delivery.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

delivery/urls.py
# delivery/urls.py

from django.urls import path
from delivery.views import (
    IndexView,
    CategoryFoodView,
    DetailFoodView
    )

app_name = 'delivery'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    # path('delivery/<int:pk>/', PostDetailView.as_view(), name='delivery_detail'),
    path('categories/<str:category_slug>/',
         CategoryFoodView.as_view(), name='category_food'),
    # path('tags/', TagListView.as_view(), name='tag_list'),
    path('foods/<str:food_name>/',
         DetailFoodView.as_view(), name='detail_food'),
]

delivery/models.py
# blog/models.py

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.core import validators
from django.db import models
from django.urls import reverse

class Category(models.Model):
    kind = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.kind


class Food(models.Model):
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    name = models.CharField(max_length=255)
    price = models.IntegerField(default=0)
    description = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    published_at = models.DateTimeField(blank=True, null=True)
    image = models.ImageField(
        upload_to='food_images/', null=True, blank=True)
    is_sale = models.BooleanField(default=True)

    class Meta:
        ordering = ['-created_at']

    def save(self, *args, **kwargs):
        if self.is_sale and not self.published_at:
            self.published_at = timezone.now()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class Invoice(models.Model):
    customer = models.CharField(
        verbose_name='顧客名',
        max_length=100,
    )

    sub_total = models.IntegerField(
        verbose_name='小計',
    )

    tax = models.IntegerField(
        verbose_name='消費税',
    )

    total_amount = models.IntegerField(
        verbose_name='合計金額',
    )

    created_by = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='作成者',
    )

    created_at = models.DateTimeField(
        verbose_name='登録日',
        auto_now_add=True
    )

    def __str__(self):
        return self.customer

    class Meta:
        verbose_name = 'Order'
        verbose_name_plural = 'Order'

    def get_absolute_url(self):
        return reverse('detail', args=[str(self.id)])


class InvoiceDetail(models.Model):
    invoice = models.ForeignKey(
        Invoice,
        on_delete=models.CASCADE)

    food = models.ForeignKey(
        Food,
        verbose_name='商品',
        on_delete=models.CASCADE,
    )

    unit_price = models.IntegerField(
        verbose_name='単価',
        validators=[validators.MinValueValidator(0)],
    )

    quantity = models.IntegerField(
        verbose_name='数量',
        validators=[validators.MinValueValidator(0)],
    )

    amount = models.IntegerField(
        verbose_name='金額',
    )

delivery/views.py
# delivery/views.py

from django.db.models import Count, Q
from django.http import Http404
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.shortcuts import get_object_or_404, redirect

from delivery.models import (
    Food,
    Category
    )

class IndexView(ListView):
    model = Food
    template_name = 'delivery/index.html'

class CategoryFoodView(ListView):
    model = Food
    template_name = 'delivery/category_food.html'

    def get_queryset(self):
        category_slug = self.kwargs['category_slug']
        self.category = get_object_or_404(Category, slug=category_slug)
        qs = super().get_queryset().filter(category=self.category)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = self.category
        return context

class DetailFoodView(ListView):
    model = Food
    template_name = 'delivery/food_detail.html'

    def get_queryset(self):
        food_name = self.kwargs['food_name']
        self.food = get_object_or_404(Food, name=food_name)
        qs = super().get_queryset().filter(name=self.food)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['food'] = self.food
        return context

delivery/templates/delivery/category_food.html
{% extends "base.html" %}
{% block title %}{{ block.super }}{% endblock %}
{% block description %}マイブログです。毎日更新します。{% endblock %}

{% load static %}

{% block content %}
<br>
<!-- ロード中に表示する内容 -->
<div id="loading">
  <p class="btn btn-default btn-lg">
    <i class="zmdi zmdi-rotate-right zmdi-hc-spin"></i>
  </p>
</div>

<ul id="gallery">
  {% for food in object_list %}
  <li class="item">
  <div class="hover11 column">
    <figure>
      <a href="{% url 'delivery:detail_food' food.name %}">
        <img src="{{ food.image.url }}">
      </a>
      <p>{{ food.name }}</p>
      <figcaption>{{ food.price }} RWF</figcaption>
    </figure>
  </div>
  </li>
  {% endfor %}
</ul>
{% endblock %}

delivery/templates/delivery/food_detail.html
{% extends "base.html" %}

{% load static %}
{% load bootstrap4 %}

{% block content %}
<br>
<ul id="gallery">
  {% for food in object_list %}
  <li class="item">
      <figure>
        <img src="{{ food.image.url }}">
        <p>{{ food.name }}</p>
        <figcaption>{{ food.price }} RWF</figcaption>
      </figure>
  </li>
  {% endfor %}
</ul>

{% endblock %}

delivery/templates/delivery/index.html
<!-- delivery/index.html -->

{% extends "base.html" %}
{% block title %}{{ block.super }}{% endblock %}
{% block description %}マイブログです。毎日更新します。{% endblock %}

{% load static %}

{% block content %}
<br>
{% include "delivery/snippets/gallery.html" %}
{% endblock %}

delivery/templates/delivery/snippets/gallery.html
{% load static %}
{% load humanize %}

<!-- ロード中に表示する内容 -->
<div id="loading">
  <p class="btn btn-default btn-lg">
    <i class="zmdi zmdi-rotate-right zmdi-hc-spin"></i>
  </p>
</div>

<ul id="gallery">
  {% for food in object_list %}
  <li class="item">
    <div class="hover11 column">
      <figure>
        <a href="{% url 'delivery:detail_food' food.name %}">
          <img src="{{ food.image.url }}">
        </a>
        <p>{{ food.name }}</p>
        <figcaption>{{ food.price|intcomma:False }} RWF</figcaption>
      </figure>
    </div>
  </li>
  {% endfor %}
</ul>

delivery/templates/delivery/snippets/main_food_list.html
{% load static %}

<ul id="gallery">
  {% for food in object_list %}
  <img src="{{ food.image.url }}">
  <!--<p>{{ food.name }}</p>-->
  <!--<p>{{ food.price }} RWF</p>-->
  {% endfor %}
</ul>

delivery/templates/delivery/snippets/sidebar.html
<div class="card mb-3">
  <div class="card-header">
    Category
  </div>
  <ul class="list-group list-group-flush">
    {% for category in categories|dictsort:"id" %}
    <li class="list-group-item d-flex justify-content-between align-items-center">
      <a href="{% url 'delivery:category_food' category.kind %}" class="card-link">{{ category.slug }}</a>
      <span class="badge badge-primary badge-pill">{{ category.num_foods }}</span>
    </li>
    {% endfor %}
  </ul>
</div>

templates/base.html
<!-- templates/base.html -->
{% load static %}

<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}ASIAN-KITCHEN-DELIVERY{% endblock %}</title>
    <meta name="description" content="{% block description %}{% endblock %}">
    <link rel="icon" href="{% static 'delivery/img/favicon.ico' %}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/material-design-iconic-font/2.2.0/css/material-design-iconic-font.min.css">
    <link rel="stylesheet" href="{% static 'delivery/css/delivery.css' %}">
    <!-- カートのCSSうまく連携できないので -->
    <style type="text/css">
      .cartbottun {
        position: fixed;
        right: 20px;
        top: 10px;
      }
      .cartbottun img {
        width: 30px;
        height: auto;
      }
      .cartbottun img:hover {
        opacity: 0.5;
      }
    </style>　
  </head>
  <body>
    <div class="cartbottun">
      <a href="/">
        <img src="{% static 'delivery/img/cartbottun.png' %}" alt="cartbottun">
      </a>
    </div>
    <a href="/">
    <center><img src="{% static 'delivery/img/logo.png' %}"
                 width="240" height=auto
                 vspace="80"></center>
    </a>

    {% include "base/navbar_v3.html" %}

    {% block content %}
    {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="/static/delivery/js/masonry.pkgd.min.js"></script>
    <script src="/static/delivery/js/imagesloaded.pkgd.min.js"></script>
    <script src="/static/delivery/js/func.js"></script>
  </body>
</html>

templates/base/navbar.html
<!-- templates/base/navbar.html -->

<nav class="navbar navbar-expand-lg navbar-light bg-light mb-4">
  <a class="navbar-brand" href="/">MyBlog</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

templates/base/navbar_v2.html
<nav class="navbar navbar-expand-lg navbar-light bg-light rounded">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="ナビゲーションの切替">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-md-center" id="navbar">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="#">ナビゲーションの中央揃え <span class="sr-only">(現位置)</span></a>
        </li>
        <li class="nav-item">
        <a class="nav-link" href="#">リンク</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">無効</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">ドロップダウン</a>
          <div class="dropdown-menu" aria-labelledby="dropdown">
            <a class="dropdown-item" href="#">リンク1</a>
            <a class="dropdown-item" href="#">リンク2</a>
            <a class="dropdown-item" href="#">リンク3</a>
          </div>
        </li>
      </ul>
    </div>
  </nav>

templates/base/navbar_v3.html
<nav class="navbar navbar-expand-lg navbar-light bg-light rounded">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="ナビゲーションの切替">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse justify-content-md-center" id="navbar">
    <ul class="navbar-nav">
      {% for category in categories|dictsort:"id" %}
      <li class="nav-item active">
        <a href="{% url 'delivery:category_food' category.slug %}" class="card-link">
          <font face="Comic Sans MS" color="green">{{ category.kind }}</font>
        </a>
        <span class="badge badge-success badge-pill">
          <font face="Comic Sans MS" >{{ category.num_foods }}</font></span>　　
      </li>
      {% endfor %}
    </ul>
  </div>
</nav>